version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-test-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-test-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: report coverage
          when: always
          command: bash <(curl -s https://codecov.io/bash)
  deploy:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-deploy-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install --only=production
      - save_cache:
          key: dependency-cache-deploy-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: install serverless
          command: sudo npm install -g serverless
      - run:
          name: install serverless plugins
          command: npm install serverless-prune-plugin
      - run:
          name: deploy
          command: serverless deploy --stage production --region $SERVERLESS_DEPLOY_REGION

workflows:
  version: 2
  test and deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                master
